{"uuid": "e426959d-a092-4f07-83dd-be5d0606621d", "counter": 36, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: cannot concatenate 'str' and 'int' objects\u001b[0m\r\n\u001b[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\\\", line 114, in <module>\\n    _ansiballz_main()\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\\\", line 106, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\\\", line 49, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\\"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\\\", line 118, in <module>\\n  File \\\"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\\\", line 115, in main\\n  File \\\"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\\\", line 81, in ensure\\n  File \\\"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\\\", line 61, in build_zone\\nTypeError: cannot concatenate 'str' and 'int' objects\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "ba20d370-7b10-42a6-b56b-27f36363c135", "event": "runner_on_failed", "event_data": {"playbook": "integrations.yml", "playbook_uuid": "b8e341fc-734d-4bd8-8737-978479a63bf9", "play": "Run tests(s)", "play_uuid": "1c1b0dec-55e8-82a2-f7ad-000000000009", "play_pattern": "containers", "task": "TEST1 | create zone", "task_uuid": "1c1b0dec-55e8-82a2-f7ad-00000000003a", "task_action": "dnszone", "task_args": "", "task_path": "/home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml:10", "host": "dnszone_dnszone_1", "remote_addr": "dnszone_dnszone_1", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 61, in build_zone\nTypeError: cannot concatenate 'str' and 'int' objects\n", "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576548.0384893-154229960511527/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_HovCOG/__main__.py\", line 61, in build_zone\nTypeError: cannot concatenate 'str' and 'int' objects\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "ignore_errors": null, "event_loop": null, "pid": 25351}, "pid": 25351, "created": "2019-08-12T02:22:29.583984", "parent_uuid": "1c1b0dec-55e8-82a2-f7ad-00000000003a"}