{"uuid": "2fbb3c55-e54f-4c47-974c-c82674c6ec56", "counter": 36, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'modules' is not defined\u001b[0m\r\n\u001b[0;31mfatal: [dnszone_dnszone_1]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\\\", line 114, in <module>\\n    _ansiballz_main()\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\\\", line 106, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\\\", line 49, in invoke_module\\n    imp.load_module('__main__', mod, module, MOD_DESC)\\n  File \\\"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\\\", line 118, in <module>\\n  File \\\"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\\\", line 115, in main\\n  File \\\"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\\\", line 81, in ensure\\n  File \\\"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\\\", line 63, in build_zone\\nNameError: global name 'modules' is not defined\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 34, "end_line": 36, "runner_ident": "4bc55405-6042-4479-bc32-e3429bfdb0bc", "event": "runner_on_failed", "event_data": {"playbook": "integrations.yml", "playbook_uuid": "9e5564a3-dd69-43d5-aeea-da3c12ddf135", "play": "Run tests(s)", "play_uuid": "1c1b0dec-55e8-9f3c-ea54-000000000009", "play_pattern": "containers", "task": "TEST1 | create zone", "task_uuid": "1c1b0dec-55e8-9f3c-ea54-00000000003a", "task_action": "dnszone", "task_args": "", "task_path": "/home/phil/git/ansible-modules/tests/integrations/dnszone/tasks.yml:10", "host": "dnszone_dnszone_1", "remote_addr": "dnszone_dnszone_1", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 63, in build_zone\nNameError: global name 'modules' is not defined\n", "exception": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565576655.6686108-124670634291358/AnsiballZ_dnszone.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 118, in <module>\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 115, in main\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 81, in ensure\n  File \"/tmp/ansible_dnszone_payload_Ew2MlD/__main__.py\", line 63, in build_zone\nNameError: global name 'modules' is not defined\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "ignore_errors": null, "event_loop": null, "pid": 28378}, "pid": 28378, "created": "2019-08-12T02:24:17.125632", "parent_uuid": "1c1b0dec-55e8-9f3c-ea54-00000000003a"}